# Generated by Django 6.0.3 on 2026-04-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('validee', 'Validée'), ('rejetee', 'Rejetée'), ('en_preparation', 'En préparation'), ('livree', 'Livrée')], default='en_attente', max_length=20)),
                ('numero_assurance', models.CharField(blank=True, max_length=100)),
                ('nom_assurance', models.CharField(blank=True, max_length=100)),
                ('prix_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
