# Generated by Django 6.0.3 on 2026-04-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_commande_opticien'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='methode_paiement',
            field=models.CharField(blank=True, choices=[('carte_bancaire', 'Carte bancaire'), ('orange_money', 'Orange Money'), ('wave', 'Wave'), ('free_money', 'Free Money')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='commande',
            name='telephone_paiement',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
