# Generated by Django 6.0.3 on 2026-04-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ordonnances/')),
                ('oeil_droit_sphere', models.FloatField(blank=True, null=True)),
                ('oeil_droit_cylindre', models.FloatField(blank=True, null=True)),
                ('oeil_droit_axe', models.FloatField(blank=True, null=True)),
                ('oeil_gauche_sphere', models.FloatField(blank=True, null=True)),
                ('oeil_gauche_cylindre', models.FloatField(blank=True, null=True)),
                ('oeil_gauche_axe', models.FloatField(blank=True, null=True)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('validee', models.BooleanField(default=False)),
            ],
        ),
    ]
