# Generated by Django 6.0.3 on 2026-04-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
