# Generated by Django 6.0.3 on 2026-04-10 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assurance', '0001_initial'),
        ('users', '0002_user_date_naissance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='compagnie_assurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assures', to='assurance.compagnieassurance'),
        ),
        migrations.AddField(
            model_name='user',
            name='numero_police',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
