# Generated by Django 6.0.3 on 2026-04-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('marque', models.CharField(max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forme', models.CharField(choices=[('ronde', 'Ronde'), ('carree', 'Carrée'), ('ovale', 'Ovale'), ('rectangulaire', 'Rectangulaire')], max_length=20)),
                ('couleur', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='montures/')),
                ('description', models.TextField(blank=True)),
                ('stock', models.IntegerField(default=0)),
                ('disponible', models.BooleanField(default=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
