# Generated by Django 5.2 on 2026-04-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='ordonnances/')),
                ('texte_extrait', models.TextField(blank=True)),
                ('date_scan', models.DateTimeField(auto_now_add=True)),
                ('sphere_od', models.FloatField(blank=True, null=True)),
                ('cylindre_od', models.FloatField(blank=True, null=True)),
                ('axe_od', models.FloatField(blank=True, null=True)),
                ('sphere_og', models.FloatField(blank=True, null=True)),
                ('cylindre_og', models.FloatField(blank=True, null=True)),
                ('axe_og', models.FloatField(blank=True, null=True)),
                ('addition', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
