# Generated by Django 6.0.3 on 2026-08-24 19:21

import ordonnances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordonnances', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordonnance',
            options={'ordering': ['-date_upload']},
        ),
        migrations.AlterField(
            model_name='ordonnance',
            name='image',
            field=models.ImageField(storage=ordonnances.models.stockage_prive, upload_to=ordonnances.models.chemin_ordonnance),
        ),
    ]
