# Generated by Django 5.2 on 2026-04-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_preparation', 'En préparation'), ('expedier', 'Expédiée'), ('livrer', 'Livrée')], default='en_attente', max_length=20),
        ),
    ]
