# Generated by Django 6.0.4 on 2026-04-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0003_alter_commande_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='is_assurance_utilisee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commande',
            name='part_assurance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='commande',
            name='part_client',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='commande',
            name='remise_famille',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
