# Generated by Django 6.0.4 on 2026-04-17 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0004_commande_is_assurance_utilisee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='mode_paiement',
            field=models.CharField(choices=[('orange_money', 'Orange Money'), ('paypal', 'PayPal'), ('carte_bancaire', 'Carte Bancaire'), ('espece', 'Espèces à la livraison')], default='carte_bancaire', max_length=20),
        ),
        migrations.AddField(
            model_name='commande',
            name='nb_lunettes_famille',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='commande',
            name='nb_membres_famille',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='commande',
            name='type_livraison',
            field=models.CharField(choices=[('expedition', 'Expédition'), ('domicile', 'Livraison Domicile')], default='expedition', max_length=20),
        ),
        migrations.AlterField(
            model_name='commande',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_preparation', 'En préparation'), ('expedier', 'Expédiée'), ('livrer', 'Livrée')], default='en_attente', max_length=20),
        ),
    ]
