# Generated by Django 6.0.3 on 2026-04-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0004_add_methode_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='adresse_livraison',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='commande',
            name='methode_paiement',
            field=models.CharField(blank=True, choices=[('carte_bancaire', 'Carte bancaire'), ('orange_money', 'Orange Money'), ('wave', 'Wave')], default='', max_length=20),
        ),
    ]
