# Generated by Django 6.0.3 on 2026-07-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0007_add_verres'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='conception_verres',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='commande',
            name='type_commande',
            field=models.CharField(choices=[('vue', 'Lunettes de vue'), ('style', 'Style / Solaire')], default='vue', max_length=10),
        ),
    ]
