# Generated by Django 6.0.3 on 2026-07-26 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commandes', '0008_commande_conception_verres_commande_type_commande'),
        ('montures', '0006_alter_monture_ajoute_par'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='monture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='montures.monture'),
        ),
    ]
