# Generated by Django 6.0.3 on 2026-08-24 19:21

import famille.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('famille', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupefamille',
            name='code_invitation',
            field=models.CharField(default=famille.models.generer_code, max_length=8, unique=True),
        ),
    ]
