# Generated by Django 6.0.3 on 2026-04-04 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompagnieAssurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('taux_prise_charge', models.DecimalField(decimal_places=2, help_text='Pourcentage pris en charge (ex: 80.00 = 80%)', max_digits=5)),
                ('plafond_annuel', models.DecimalField(blank=True, decimal_places=2, help_text='Plafond annuel de remboursement en CFA', max_digits=10, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Compagnie assurance',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='DemandeRemboursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_police', models.CharField(blank=True, max_length=100)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_rembourse', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('montant_patient', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('soumise', "Soumise à l'assurance"), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée'), ('remboursee', 'Remboursée')], default='en_attente', max_length=20)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='remboursement', to='commandes.commande')),
                ('compagnie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assurance.compagnieassurance')),
            ],
            options={
                'verbose_name': 'Demande de remboursement',
                'ordering': ['-date_soumission'],
            },
        ),
    ]
