# Generated by Django 5.2 on 2026-04-09 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('montures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssaiVirtuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_utilisateur', models.ImageField(blank=True, null=True, upload_to='essais/')),
                ('image_resultat', models.ImageField(blank=True, null=True, upload_to='essais/resultats/')),
                ('date_essai', models.DateTimeField(auto_now_add=True)),
                ('monture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='montures.monture')),
            ],
        ),
    ]
