# Generated by Django 6.0.3 on 2026-04-04 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoutiqueOpticien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('slogan', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='boutiques/')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('opticien', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boutique', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
