# Generated by Django 6.0.4 on 2026-04-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assurance_nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='assurance_numero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='code_famille',
            field=models.CharField(blank=True, help_text='Partagez ce code avec votre famille pour des réductions.', max_length=50, null=True),
        ),
    ]
