# Generated by Django 6.0.3 on 2026-07-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_add_assurance_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='statut_validation',
            field=models.CharField(choices=[('approuve', 'Approuvé'), ('en_attente', 'En attente de validation'), ('rejete', 'Rejeté')], default='approuve', max_length=20),
        ),
    ]
