# Generated by Django 6.0.4 on 2026-04-17 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_assurance_nom_user_assurance_numero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code_famille',
            field=models.CharField(blank=True, help_text='Code obsolète, utilisez le lien famille.', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Famille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code_unique', models.CharField(max_length=10, unique=True)),
                ('nb_membres', models.PositiveIntegerField(default=1)),
                ('nb_lunettes_prevues', models.PositiveIntegerField(default=1)),
                ('chef_famille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familles_gerees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='famille',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to='users.famille'),
        ),
    ]
