# Generated by Django 6.0.3 on 2026-08-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_statut_validation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tokens_valides_apres',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
