# Generated by Django 6.0.3 on 2026-04-04 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MontureImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='montures/galerie/')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galerie', to='montures.monture')),
            ],
            options={
                'ordering': ['ordre', 'created_at'],
            },
        ),
    ]
