# Generated by Django 6.0.3 on 2026-04-04 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montures', '0002_montureimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monture',
            name='ajoute_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='montures_ajoutees', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par'),
        ),
    ]
