# Generated by Django 6.0.3 on 2026-04-08 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montures', '0003_monture_ajoute_par'),
    ]

    operations = [
        migrations.AddField(
            model_name='monture',
            name='categorie',
            field=models.CharField(choices=[('adulte', 'Adulte'), ('enfant', 'Enfant'), ('sport', 'Sport'), ('luxe', 'Luxe')], default='adulte', max_length=20),
        ),
    ]
