# Generated by Django 6.0.3 on 2026-07-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('montures', '0004_add_categorie_to_monture'),
    ]

    operations = [
        migrations.AddField(
            model_name='monture',
            name='type',
            field=models.CharField(choices=[('vue', 'Lunettes de vue'), ('solaire', 'Solaire / Style'), ('mixte', 'Mixte')], default='mixte', max_length=10),
        ),
    ]
