# Generated by Django 6.0.3 on 2026-08-07 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('montures', '0006_alter_monture_ajoute_par'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chemin', models.CharField(db_index=True, max_length=255)),
                ('visiteur', models.CharField(db_index=True, max_length=64)),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('monture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visites', to='montures.monture')),
                ('opticien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visites_recues', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visite',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['-date', 'opticien'], name='stats_visit_date_05b08d_idx')],
            },
        ),
    ]
